### ISSUE TITLE
The template for "response to stimulus" generates an empty ontology file

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/webulous#13]
The Webulous template for "response to stimulus" generates an empty OWL file. An example template can be found at: https://docs.google.com/spreadsheets/d/1guY9ioJZH7nRo_vAO3fOhWj9A7EngtbJ7ZxD-D7ZrHM/edit#gid=1029315491

**Comment by siiraa** [comment]
Additional info:

Your data submitted to webulous template Add EFO response to stimulus has completed with status: FAILED

[Failed to validate pattern: Response: Recognition exception at line 1 char position in line 0]

**Comment by simonjupp** [comment]
Typo in the OPPL, this is now fixed.
