### ISSUE TITLE
Review of Webulous templates (issue with import CHEBI terms)

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/webulous#16]
Some of the Webulous templates, in particular the import templates, do not seem to be working correctly. Most notably, this has been seen by @paolaroncaglia in the CHEBI import (https://github.com/EBISPOT/efo/issues/150) where no annotations from CHEBI have been extracted.

It may be worth checking each individual template to ensure that all necessary information is updated and working.

**Comment by paolaroncaglia** [comment]
Thanks @zoependlington .
For reference, the owl file generated from the "Import ChEBI" template (https://docs.google.com/spreadsheets/d/1qCnelYqd7hG-7Kq_t964tICJGI-yKZirF9Tcdje6YMQ/edit#gid=1564195025) is at ftp://ftp.ebi.ac.uk/pub/databases/spot/webulous/efo/5bcf0e7fe4b0e435a7fcea5b.owl.

**Comment by simonjupp** [comment]
Need new chebi import that uses robot for EFO 3 as Webulous import doesn't include all axioms when building a subset for import.
